### ISSUE TITLE
user_pin.register is not a function

### ISSUE THREAD

**Issue by somenathghosh** [jrpruit1/checklist#7]
I just did following

Clone the repo --> npm install --> npm start.

Getting following error:

`TypeError: user_pin.register is not a function
    at /Users/somenathghosh/Documents/checklist/server.js:57:14
    at done (/Users/somenathghosh/Documents/checklist/node_modules/hapi/node_modules/items/lib/index.js:30:25)
    at Object.module.exports.register (/Users/somenathghosh/Documents/checklist/node_modules/hapi-seneca/index.js:86:5)
    at /Users/somenathghosh/Documents/checklist/node_modules/hapi/lib/plugin.js:235:14
    at iterate (/Users/somenathghosh/Documents/checklist/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/Users/somenathghosh/Documents/checklist/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (/Users/somenathghosh/Documents/checklist/node_modules/hapi/lib/plugin.js:221:11)
    at Object.<anonymous> (/Users/somenathghosh/Documents/checklist/server.js:47:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

`

2 info using npm@3.7.3
3 info using node@v5.8.0

Please help.

Thanks,
Somenath

**Comment by mlinnen** [comment]
I get the same error taking the same steps on a windows machine.

**Comment by heriipurnama** [comment]
get the same error taking the same steps 

> heriipurnama@helloween:~/Documents/node/checklist$ npm start
> checklist@0.0.1 start /home/heriipurnama/Documents/node/checklist
> node server.js
> 
> /2016-04-04T02:37:06.257Z eyej6o1wyseq/1459737426235/8377/- INFO  hello   Seneca/2.0.0 > /eyej6o1wyseq/1459737426235/8377/-  
> /home/heriipurnama/Documents/node/checklist/server.js:57
>   user_pin({
>     ^
> 
> TypeError: user_pin is not a function
> at /home/heriipurnama/Documents/node/checklist/server.js:57:5
>     > at done (/home/heriipurnama/Documents/node/checklist/node_modules/hapi/node_modules/items/lib/index.js:30:25)
>  at Object.module.exports.register (/home/heriipurnama/Documents/node/checklist/node_modules/hapi-seneca/index.js:86:5)
>   at /home/heriipurnama/Documents/node/checklist/node_modules/hapi/lib/plugin.js:235:14
> at iterate (/home/heriipurnama/Documents/node/checklist/node_modules/hapi/node_modules/items/lib/index.js:35:13)
> at Object.exports.serial (/home/heriipurnama/Documents/node/checklist/node_modules/hapi/node_modules/items/lib/index.js:38:9)
>   at internals.Plugin.register (/home/heriipurnama/Documents/node/checklist/node_modules/hapi/lib/plugin.js:221:11)
> at Object.<anonymous> (/home/heriipurnama/Documents/node/checklist/server.js:47:5)
>     > at Module._compile (module.js:435:26)
>    at Object.Module._extensions..js (module.js:442:10)
> `
